async function Fsf_14_Web(moduleArg={}){var moduleRtn;var h=moduleArg,ea=!!globalThis.window,k=!!globalThis.WorkerGlobalScope,l=globalThis.process?.versions?.node&&globalThis.process?.type!="renderer",m=k&&globalThis.name=="em-pthread";if(l){let {createRequire:a}=await import("node:module");var require=a(import.meta.url),worker_threads=require("node:worker_threads");globalThis.Worker=worker_threads.Worker;m=(k=!worker_threads.isMainThread)&&worker_threads.workerData=="em-pthread"}h.listen||(h.listen=a=>console.log(a));
h.onError||(h.onError=a=>console.error(a));h.getRecommendedNnue=(a=0)=>fa(ha(a))||void 0;h.setNnueBuffer=function(a,b=0){if(!a)throw Error("buf is null");if(a.byteLength<=0)throw Error(`${a.byteLength} bytes?`);var c=ia(a.byteLength);if(!c)throw Error(`could not allocate ${a.byteLength} bytes`);q();h.HEAPU8.set(a,c);ja(c,a.byteLength,b)};h.uci=function(a){var b=ka(a)+1,c=ia(b);if(!c)throw Error(`Could not allocate ${b} bytes`);t(a,c,b);la(c)};h.print=a=>h.listen?.(a);h.printErr=a=>h.onError?.(a);
var ma=[],na="./this.program",oa=(a,b)=>{throw b;},pa=import.meta.url,qa="",ra,sa;
if(l){var fs=require("node:fs");pa.startsWith("file:")&&(qa=require("node:path").dirname(require("node:url").fileURLToPath(pa))+"/");sa=a=>{a=ta(a)?new URL(a):a;return fs.readFileSync(a)};ra=async a=>{a=ta(a)?new URL(a):a;return fs.readFileSync(a,void 0)};process.argv.length>1&&(na=process.argv[1].replace(/\\/g,"/"));ma=process.argv.slice(2);oa=(a,b)=>{process.exitCode=a;throw b;}}else if(ea||k){try{qa=(new URL(".",pa)).href}catch{}l||(k&&(sa=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType=
"arraybuffer";b.send(null);return new Uint8Array(b.response)}),ra=async a=>{a=await fetch(a,{credentials:"same-origin"});if(a.ok)return a.arrayBuffer();throw Error(a.status+" : "+a.url);})}var ua=console.log.bind(console),va=console.error.bind(console);if(l){var wa=require("node:util"),xa=a=>typeof a=="object"?wa.inspect(a):a;ua=(...a)=>fs.writeSync(1,a.map(xa).join(" ")+"\n");va=(...a)=>fs.writeSync(2,a.map(xa).join(" ")+"\n")}var ya=ua,u=va,v,za=!1,w,ta=a=>a.startsWith("file://");
function q(){x.buffer!=y.buffer&&Aa()}var Ba,Ca;if(l&&m){globalThis.self=globalThis;var Da=worker_threads.parentPort;globalThis.postMessage||(Da.on("message",a=>globalThis.onmessage?.({data:a})),globalThis.postMessage=a=>Da.postMessage(a));process.on("uncaughtException",a=>{postMessage({ga:8,error:a});process.exit(1)})}var Ea;
if(m){var Fa=!1;self.onunhandledrejection=b=>{throw b.reason||b;};function a(b){try{var c=b.data,d=c.ga;if(d==1){let e=[];self.onmessage=f=>e.push(f);Ea=()=>{postMessage({ga:3});for(let f of e)a(f);self.onmessage=a};for(let f of c.Ia)if(!h[f]||h[f].proxy)h[f]=(...g)=>{postMessage({ga:9,Ha:f,args:g})},f=="print"&&(ya=h[f]),f=="printErr"&&(u=h[f]);x=c.Va;Aa();v=c.Wa;Ga();Ha()}else if(d==2){Ia(c.ja);Ja(c.ja,0,0,1,0,0);Ka();La(c.ja);Fa||=!0;try{Ma(c.Qa,c.sa)}catch(e){if(e!="unwind")throw e;}}else d==
4?Fa&&Na():d&&(u(`worker: received unknown command ${d}`),u(c))}catch(e){throw Oa(),e;}}self.onmessage=a}var Pa=!1,Qa=!1;function Aa(){var a=x.buffer;y=new Int8Array(a);Ra=new Int16Array(a);h.HEAPU8=Sa=new Uint8Array(a);new Uint16Array(a);A=new Int32Array(a);B=new Uint32Array(a);new Float32Array(a);Ta=new Float64Array(a);C=new BigInt64Array(a);new BigUint64Array(a)}
function Ua(){Pa=!0;m?Ea():(h.noFSInit||Va||(Va=!0,Wa("/dev/tty","/dev/stdin"),Wa("/dev/tty","/dev/stdout"),Wa("/dev/tty1","/dev/stderr"),Xa("/dev/stdin",0),Xa("/dev/stdout",1),Xa("/dev/stderr",1)),D.D(),Ya=!1)}function Za(a){a=`Aborted(${a})`;u(a);za=!0;a=new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");Ca?.(a);throw a;}var $a;
async function ab(a){try{var b=await ra(a);return new Uint8Array(b)}catch{}if(sa)a=sa(a);else throw"both async and sync fetching of the wasm failed";return a}async function bb(a,b){try{var c=await ab(a);return await WebAssembly.instantiate(c,b)}catch(d){u(`failed to asynchronously prepare wasm: ${d}`),Za(d)}}
async function cb(a){var b=$a;if(!l)try{var c=fetch(b,{credentials:"same-origin"});return await WebAssembly.instantiateStreaming(c,a)}catch(d){u(`wasm streaming compile failed: ${d}`),u("falling back to ArrayBuffer instantiation")}return bb(b,a)}function db(){eb={B:fb,e:gb,x:hb,y:ib,o:jb,k:kb,A:lb,h:mb,q:nb,f:ob,j:La,i:pb,r:qb,s:rb,C:sb,g:tb,n:ub,c:vb,z:wb,w:xb,l:yb,m:zb,b:Ab,d:Bb,v:Cb,t:Db,u:Eb,a:x,p:Fb};return{a:eb}}
async function Ga(){function a(d,e){D=d.exports;Gb.push(D.J);d=D;h.__Z10js_getlinev=d.E;h._main=d.F;la=h._uci=d.G;ja=h._setNnueBuffer=d.H;ha=h._getRecommendedNnue=d.I;Hb=d.K;Ib=h.__emscripten_proxy_main=d.L;Jb=d.N;Ja=d.O;Kb=d.P;Oa=d.Q;Lb=d.R;ia=h._malloc=d.S;Mb=d.T;Nb=d.U;Ob=d.V;Pb=d.W;Qb=d.X;Rb=d.Y;Sb=d.Z;Tb=d._;Ub=d.$;Vb=d.aa;Wb=d.M;v=e;return D}var b=db();if(h.instantiateWasm)return new Promise(d=>{h.instantiateWasm(b,(e,f)=>{d(a(e,f))})});if(m){var c=new WebAssembly.Instance(v,db());return a(c,
v)}$a??=h.locateFile?h.locateFile?h.locateFile("fsf_14.wasm",qa):qa+"fsf_14.wasm":(new URL("fsf_14.wasm",import.meta.url)).href;return function(d){return a(d.instance,d.module)}(await cb(b))}class Xb{name="ExitStatus";constructor(a){this.message=`Program terminated with exit(${a})`;this.status=a}}
var Ra,A,C,y,Ta,B,Sa,Yb=a=>{a.terminate();a.onmessage=()=>{}},Zb=[],ac=a=>{if(E.length==0){if(h.mainScriptUrlOrBlob){var b=h.mainScriptUrlOrBlob;typeof b!="string"&&(b=URL.createObjectURL(b));b=new Worker(b,{type:"module",workerData:"em-pthread",name:"em-pthread"})}else b=new Worker(new URL("fsf_14.js",import.meta.url),{type:"module",workerData:"em-pthread",name:"em-pthread"});E.push(b);$b(b)}b=E.pop();if(!b)return 6;H[a.ja]=b;b.ja=a.ja;b.postMessage({ga:2,Qa:a.Pa,sa:a.sa,ja:a.ja},a.Ta);
return 0},I=0,xb=()=>I>0,J=(a,b,...c)=>{var d=8*c.length*2,e=Vb(),f=Ub(d),g=f>>3,n;for(n of c)typeof n=="bigint"?((q(),C)[g++]=1n,(q(),C)[g++]=n):((q(),C)[g++]=0n,(q(),Ta)[g++]=n);a=Nb(a,0,d,f,b);Tb(e);return a};function Fb(a){if(m)return J(0,1,a);w=a;I>0||(bc(),h.onExit?.(a),za=!0);oa(a,new Xb(a))}function cc(a){if(m)return J(1,0,a);--I;Ab(a)}
var Ab=a=>{w=a;if(m)throw cc(a),"unwind";if(!(I>0)){Jb();Va=!1;Lb(0);for(var b of K)b&&dc(b);for(var c of Object.values(L))clearTimeout(c.id);bc();b=Hb();Kb(0,0,0,1);ec||Atomics.notify((q(),A),b>>2);Qa=!0}Fb(a)},ec=!Atomics.waitAsync||globalThis.navigator?.userAgent&&Number((navigator.userAgent.match(/Chrom(e|ium)\/([0-9]+)\./)||[])[2])<91,E=[],Gb=[],H={},bc=()=>{for(var a of Object.values(H))Yb(a);for(a of E)Yb(a);E=[];H={}},fc=a=>{var b=a.ja;delete H[b];E.push(a);a.ja=0;l&&a.unref();Ob(b)};
function Ka(){Gb.forEach(a=>a())}
var $b=a=>{new Promise(b=>{a.onmessage=f=>{var g=f.data;f=g.ga;if(g.Fa)H[g.Fa]?.postMessage(g);else if(g==="setimmediate"||g==="_si")a.postMessage(g);else switch(f){case 4:Na();break;case 5:ac(g);break;case 6:hc(()=>{fc(H[g.Sa])});break;case 3:l&&!a.Ra&&a.unref();b(a);break;case 8:a.onerror(g.error);break;case 9:h[g.Ha](...g.args);break;default:f&&u(`worker sent an unknown command ${f}`)}};a.onerror=f=>{u(`worker sent an error! ${f.filename}:${f.lineno}: ${f.message}`);throw f;};l&&(a.on("message",
f=>a.onmessage({data:f})),a.on("error",f=>a.onerror(f)));var c=[],d=["onExit","print","printErr"],e;for(e of d)h.propertyIsEnumerable(e)&&c.push(e);a.postMessage({ga:1,Ia:c,Va:x,Wa:v})})};function Ia(a){var b=(q(),B)[a+48>>2];a=(q(),B)[a+52>>2];Sb(b,b-a);Tb(b)}var ic=[],Ma=(a,b)=>{I=0;var c=ic[a];c||(ic[a]=c=Wb.get(a));a=c(b);I>0?w=a:Pb(a)},x;function jc(a,b,c,d){return m?J(2,1,a,b,c,d):fb(a,b,c,d)}
var fb=(a,b,c,d)=>{if(!globalThis.SharedArrayBuffer)return 6;var e=[];if(m&&e.length===0)return jc(a,b,c,d);a={Pa:c,ja:a,sa:d,Ta:e};return m?(a.ga=5,postMessage(a,e),0):ac(a)},O=()=>{var a=(q(),A)[+M>>2];M+=4;return a},kc=(a,b)=>{for(var c=0,d=a.length-1;d>=0;d--){var e=a[d];e==="."?a.splice(d,1):e===".."?(a.splice(d,1),c++):c&&(a.splice(d,1),c--)}if(b)for(;c;c--)a.unshift("..");return a},lc=a=>{var b=a.charAt(0)==="/",c=a.slice(-1)==="/";(a=kc(a.split("/").filter(d=>!!d),!b).join("/"))||b||(a=".");
a&&c&&(a+="/");return(b?"/":"")+a},mc=a=>{var b=/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1);a=b[0];b=b[1];if(!a&&!b)return".";b&&=b.slice(0,-1);return a+b},nc=()=>{if(l){var a=require("node:crypto");return b=>a.randomFillSync(b)}return b=>(b.set(crypto.getRandomValues(new Uint8Array(b.byteLength))),0)},oc=a=>(oc=nc())(a),pc=(...a)=>{for(var b="",c=!1,d=a.length-1;d>=-1&&!c;d--){c=d>=0?a[d]:"/";if(typeof c!="string")throw new TypeError("Arguments to path.resolve must be strings");
if(!c)return"";b=c+"/"+b;c=c.charAt(0)==="/"}b=kc(b.split("/").filter(e=>!!e),!c).join("/");return(c?"/":"")+b||"."},qc=globalThis.TextDecoder&&new TextDecoder,P=(a,b=0,c,d)=>{var e=b;c=e+c;if(d)d=c;else{for(;a[e]&&!(e>=c);)++e;d=e}if(d-b>16&&a.buffer&&qc)return qc.decode(a.buffer instanceof ArrayBuffer?a.subarray(b,d):a.slice(b,d));for(e="";b<d;)if(c=a[b++],c&128){var f=a[b++]&63;if((c&224)==192)e+=String.fromCharCode((c&31)<<6|f);else{var g=a[b++]&63;c=(c&240)==224?(c&15)<<12|f<<6|g:(c&7)<<18|f<<
12|g<<6|a[b++]&63;c<65536?e+=String.fromCharCode(c):(c-=65536,e+=String.fromCharCode(55296|c>>10,56320|c&1023))}}else e+=String.fromCharCode(c);return e},rc=[],ka=a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);d<=127?b++:d<=2047?b+=2:d>=55296&&d<=57343?(b+=4,++c):b+=3}return b},sc=(a,b,c,d)=>{if(!(d>0))return 0;var e=c;d=c+d-1;for(var f=0;f<a.length;++f){var g=a.codePointAt(f);if(g<=127){if(c>=d)break;b[c++]=g}else if(g<=2047){if(c+1>=d)break;b[c++]=192|g>>6;b[c++]=128|g&63}else if(g<=
65535){if(c+2>=d)break;b[c++]=224|g>>12;b[c++]=128|g>>6&63;b[c++]=128|g&63}else{if(c+3>=d)break;b[c++]=240|g>>18;b[c++]=128|g>>12&63;b[c++]=128|g>>6&63;b[c++]=128|g&63;f++}}b[c]=0;return c-e},tc=[];function uc(a,b){tc[a]={input:[],output:[],la:b};vc(a,wc)}
var wc={open(a){var b=tc[a.node.rdev];if(!b)throw new Q(43);a.tty=b;a.seekable=!1},close(a){a.tty.la.fsync(a.tty)},fsync(a){a.tty.la.fsync(a.tty)},read(a,b,c,d){if(!a.tty||!a.tty.la.Aa)throw new Q(60);for(var e=0,f=0;f<d;f++){try{var g=a.tty.la.Aa(a.tty)}catch(n){throw new Q(29);}if(g===void 0&&e===0)throw new Q(6);if(g===null||g===void 0)break;e++;b[c+f]=g}e&&(a.node.atime=Date.now());return e},write(a,b,c,d){if(!a.tty||!a.tty.la.xa)throw new Q(60);try{for(var e=0;e<d;e++)a.tty.la.xa(a.tty,b[c+e])}catch(f){throw new Q(29);
}d&&(a.node.mtime=a.node.ctime=Date.now());return e}},xc={Aa(){a:{if(!rc.length){var a=null;if(l){var b=Buffer.alloc(256),c=0,d=process.stdin.fd;try{c=fs.readSync(d,b,0,256)}catch(e){if(e.toString().includes("EOF"))c=0;else throw e;}c>0&&(a=b.slice(0,c).toString("utf-8"))}else globalThis.window?.prompt&&(a=window.prompt("Input: "),a!==null&&(a+="\n"));if(!a){a=null;break a}b=Array(ka(a)+1);a=sc(a,b,0,b.length);b.length=a;rc=b}a=rc.shift()}return a},xa(a,b){b===null||b===10?(ya(P(a.output)),a.output=
[]):b!=0&&a.output.push(b)},fsync(a){a.output?.length>0&&(ya(P(a.output)),a.output=[])},Ka(){return{$a:25856,bb:5,Za:191,ab:35387,Ya:[3,28,127,21,4,0,1,0,17,19,26,0,18,15,23,22,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]}},La(){return 0},Ma(){return[24,80]}},yc={xa(a,b){b===null||b===10?(u(P(a.output)),a.output=[]):b!=0&&a.output.push(b)},fsync(a){a.output?.length>0&&(u(P(a.output)),a.output=[])}},R={ia:null,ka(){return R.createNode(null,"/",16895,0)},createNode(a,b,c,d){if((c&61440)===24576||(c&61440)===4096)throw new Q(63);
R.ia||(R.ia={dir:{node:{oa:R.da.oa,ma:R.da.ma,lookup:R.da.lookup,qa:R.da.qa,rename:R.da.rename,unlink:R.da.unlink,rmdir:R.da.rmdir,readdir:R.da.readdir,symlink:R.da.symlink},stream:{ha:R.ba.ha}},file:{node:{oa:R.da.oa,ma:R.da.ma},stream:{ha:R.ba.ha,read:R.ba.read,write:R.ba.write,Ca:R.ba.Ca,Ea:R.ba.Ea}},link:{node:{oa:R.da.oa,ma:R.da.ma,readlink:R.da.readlink},stream:{}},za:{node:{oa:R.da.oa,ma:R.da.ma},stream:zc}});c=Ac(a,b,c,d);(c.mode&61440)===16384?(c.da=R.ia.dir.node,c.ba=R.ia.dir.stream,c.ea=
{}):(c.mode&61440)===32768?(c.da=R.ia.file.node,c.ba=R.ia.file.stream,c.fa=0,c.ea=R.Ga??(R.Ga=new Uint8Array(0))):(c.mode&61440)===40960?(c.da=R.ia.link.node,c.ba=R.ia.link.stream):(c.mode&61440)===8192&&(c.da=R.ia.za.node,c.ba=R.ia.za.stream);c.atime=c.mtime=c.ctime=Date.now();a&&(a.ea[b]=c,a.atime=a.mtime=a.ctime=c.atime);return c},da:{oa(a){var b={};b.dev=(a.mode&61440)===8192?a.id:1;b.ino=a.id;b.mode=a.mode;b.nlink=1;b.uid=0;b.gid=0;b.rdev=a.rdev;(a.mode&61440)===16384?b.size=4096:(a.mode&61440)===
32768?b.size=a.fa:(a.mode&61440)===40960?b.size=a.link.length:b.size=0;b.atime=new Date(a.atime);b.mtime=new Date(a.mtime);b.ctime=new Date(a.ctime);b.blksize=4096;b.blocks=Math.ceil(b.size/b.blksize);return b},ma(a,b){for(var c of["mode","atime","mtime","ctime"])b[c]!=null&&(a[c]=b[c]);b.size!==void 0&&(b=b.size,a.fa!=b&&(c=a.ea,a.ea=new Uint8Array(b),a.ea.set(c.subarray(0,Math.min(b,a.fa))),a.fa=b))},lookup(){R.ta||(R.ta=new Q(44),R.ta.stack="<generic error, no stack>");throw R.ta;},qa(a,b,c,d){return R.createNode(a,
b,c,d)},rename(a,b,c){try{var d=Bc(b,c)}catch(f){}if(d){if((a.mode&61440)===16384)for(var e in d.ea)throw new Q(55);e=Cc(d.parent.id,d.name);if(S[e]===d)S[e]=d.pa;else for(e=S[e];e;){if(e.pa===d){e.pa=d.pa;break}e=e.pa}}delete a.parent.ea[a.name];b.ea[c]=a;a.name=c;b.ctime=b.mtime=a.parent.ctime=a.parent.mtime=Date.now()},unlink(a,b){delete a.ea[b];a.ctime=a.mtime=Date.now()},rmdir(a,b){var c=Bc(a,b),d;for(d in c.ea)throw new Q(55);delete a.ea[b];a.ctime=a.mtime=Date.now()},readdir(a){return[".",
"..",...Object.keys(a.ea)]},symlink(a,b,c){a=R.createNode(a,b,41471,0);a.link=c;return a},readlink(a){if((a.mode&61440)!==40960)throw new Q(28);return a.link}},ba:{read(a,b,c,d,e){if(e>=a.node.fa)return 0;d=Math.min(a.node.fa-e,d);b.set(a.node.ea.subarray(e,e+d),c);return d},write(a,b,c,d,e,f){b.buffer===(q(),y).buffer&&(f=!1);if(!d)return 0;a=a.node;a.mtime=a.ctime=Date.now();if(f)a.ea=b.subarray(c,c+d),a.fa=d;else if(a.fa===0&&e===0)a.ea=b.slice(c,c+d),a.fa=d;else{f=e+d;var g=a.ea.length;g>=f||
(f=Math.max(f,g*(g<1048576?2:1.125)>>>0),g&&(f=Math.max(f,256)),g=a.ea.subarray(0,a.fa),a.ea=new Uint8Array(f),a.ea.set(g));a.ea.set(b.subarray(c,c+d),e);a.fa=Math.max(a.fa,e+d)}return d},ha(a,b,c){c===1?b+=a.position:c===2&&(a.node.mode&61440)===32768&&(b+=a.node.fa);if(b<0)throw new Q(28);return b},Ca(a,b,c,d,e){if((a.node.mode&61440)!==32768)throw new Q(43);a=a.node.ea;if(e&2||a.buffer!==(q(),y).buffer){d=!0;Za();e=void 0;if(!e)throw new Q(48);if(a){if(c>0||c+b<a.length)a.subarray?a=a.subarray(c,
c+b):a=Array.prototype.slice.call(a,c,c+b);(q(),y).set(a,e)}}else d=!1,e=a.byteOffset;return{gb:e,Xa:d}},Ea(a,b,c,d){R.ba.write(a,b,0,d,c,!1);return 0}}},Dc=a=>{var b=0;a&&(b|=365);return b},Ec=0,Fc=null,Gc={},K=[],Hc=1,S=null,Va=!1,Ya=!0,Q=class{name="ErrnoError";constructor(a){this.na=a}},Ic=class{shared={};node=null;get flags(){return this.shared.flags}set flags(a){this.shared.flags=a}get position(){return this.shared.position}set position(a){this.shared.position=a}},Jc=class{da={};ba={};ra=null;constructor(a,
b,c,d){a||=this;this.parent=a;this.ka=a.ka;this.id=Hc++;this.name=b;this.mode=c;this.rdev=d;this.atime=this.mtime=this.ctime=Date.now()}get read(){return(this.mode&365)===365}set read(a){a?this.mode|=365:this.mode&=-366}get write(){return(this.mode&146)===146}set write(a){a?this.mode|=146:this.mode&=-147}};
function U(a,b={}){if(!a)throw new Q(44);b.va??(b.va=!0);a.charAt(0)==="/"||(a="//"+a);var c=0;a:for(;c<40;c++){a=a.split("/").filter(n=>!!n);for(var d=Fc,e="/",f=0;f<a.length;f++){var g=f===a.length-1;if(g&&b.parent)break;if(a[f]!==".")if(a[f]==="..")if(e=mc(e),d===d.parent){a=e+"/"+a.slice(f+1).join("/");c--;continue a}else d=d.parent;else{e=lc(e+"/"+a[f]);try{d=Bc(d,a[f])}catch(n){if(n?.na===44&&g&&b.Oa)return{path:e};throw n;}!d.ra||g&&!b.va||(d=d.ra.root);if((d.mode&61440)===40960&&(!g||b.ua)){if(!d.da.readlink)throw new Q(52);
d=d.da.readlink(d);d.charAt(0)==="/"||(d=mc(e)+"/"+d);a=d+"/"+a.slice(f+1).join("/");continue a}}}return{path:e,node:d}}throw new Q(32);}function Cc(a,b){for(var c=0,d=0;d<b.length;d++)c=(c<<5)-c+b.charCodeAt(d)|0;return(a+c>>>0)%S.length}function Bc(a,b){var c=(a.mode&61440)===16384?(c=Kc(a,"x"))?c:a.da.lookup?0:2:54;if(c)throw new Q(c);for(c=S[Cc(a.id,b)];c;c=c.pa){var d=c.name;if(c.parent.id===a.id&&d===b)return c}return a.da.lookup(a,b)}
function Ac(a,b,c,d){a=new Jc(a,b,c,d);b=Cc(a.parent.id,a.name);a.pa=S[b];return S[b]=a}function Kc(a,b){return Ya?0:b.includes("r")&&!(a.mode&292)||b.includes("w")&&!(a.mode&146)||b.includes("x")&&!(a.mode&73)?2:0}function Lc(a,b){if((a.mode&61440)!==16384)return 54;try{return Bc(a,b),20}catch(c){}return Kc(a,"wx")}function V(a){a=K[a];if(!a)throw new Q(8);return a}
function Mc(a,b=-1){a=Object.assign(new Ic,a);if(b==-1)a:{for(b=0;b<=4096;b++)if(!K[b])break a;throw new Q(33);}a.fd=b;return K[b]=a}function Nc(a,b=-1){a=Mc(a,b);a.ba?.eb?.(a);return a}function Oc(a,b){var c=void 0,d=c?null:a;c??=a.da.ma;if(!c)throw new Q(63);try{c(d,b)}catch(e){if(e instanceof RangeError)throw new Q(22);throw e;}}var zc={open(a){a.ba=Gc[a.node.rdev].ba;a.ba.open?.(a)},ha(){throw new Q(70);}};function vc(a,b){Gc[a]={ba:b}}
function Pc(a,b){var c=b==="/";if(c&&Fc)throw new Q(10);if(!c&&b){var d=U(b,{va:!1});b=d.path;d=d.node;if(d.ra)throw new Q(10);if((d.mode&61440)!==16384)throw new Q(54);}b={type:a,fb:{},Da:b,Na:[]};a=a.ka(b);a.ka=b;b.root=a;c?Fc=a:d&&(d.ra=b,d.ka&&d.ka.Na.push(b))}function Qc(a,b,c){var d=U(a,{parent:!0}).node;a=a&&a.match(/([^\/]+|\/)\/*$/)[1];if(!a)throw new Q(28);if(a==="."||a==="..")throw new Q(20);var e=Lc(d,a);if(e)throw new Q(e);if(!d.da.qa)throw new Q(63);return d.da.qa(d,a,b,c)}
function W(a){return Qc(a,16895,0)}function Rc(a,b,c){typeof c=="undefined"&&(c=b,b=438);Qc(a,b|8192,c)}function Wa(a,b){if(!pc(a))throw new Q(44);var c=U(b,{parent:!0}).node;if(!c)throw new Q(44);b=b&&b.match(/([^\/]+|\/)\/*$/)[1];var d=Lc(c,b);if(d)throw new Q(d);if(!c.da.symlink)throw new Q(63);c.da.symlink(c,b,a)}
function Xa(a,b,c=438){if(a==="")throw new Q(44);if(typeof b=="string"){var d={r:0,"r+":2,w:577,"w+":578,a:1089,"a+":1090}[b];if(typeof d=="undefined")throw Error(`Unknown file open mode: ${b}`);b=d}c=b&64?c&4095|32768:0;if(typeof a=="object")d=a;else{var e=a.endsWith("/");var f=U(a,{ua:!(b&131072),Oa:!0});d=f.node;a=f.path}f=!1;if(b&64)if(d){if(b&128)throw new Q(20);}else{if(e)throw new Q(31);d=Qc(a,c|511,0);f=!0}if(!d)throw new Q(44);(d.mode&61440)===8192&&(b&=-513);if(b&65536&&(d.mode&61440)!==
16384)throw new Q(54);if(!f&&(d?(d.mode&61440)===40960?e=32:(e=["r","w","rw"][b&3],b&512&&(e+="w"),e=(d.mode&61440)===16384&&(e!=="r"||b&576)?31:Kc(d,e)):e=44,e))throw new Q(e);if(b&512&&!f){e=d;e=typeof e=="string"?U(e,{ua:!0}).node:e;if((e.mode&61440)===16384)throw new Q(31);if((e.mode&61440)!==32768)throw new Q(28);if(a=Kc(e,"w"))throw new Q(a);Oc(e,{size:0,timestamp:Date.now()})}a:{for(e=d;;){if(e===e.parent){e=e.ka.Da;var g=g?e[e.length-1]!=="/"?`${e}/${g}`:e+g:e;break a}g=g?`${e.name}/${g}`:
e.name;e=e.parent}g=void 0}b=Mc({node:d,path:g,flags:b&-131713,seekable:!0,position:0,ba:d.ba,Ua:[],error:!1});b.ba.open&&b.ba.open(b);f&&(c&=511,d=typeof d=="string"?U(d,{ua:!0}).node:d,Oc(d,{mode:c&4095|d.mode&-4096,ctime:Date.now(),cb:void 0}));return b}function dc(a){if(a.fd===null)throw new Q(8);a.wa&&(a.wa=null);try{a.ba.close&&a.ba.close(a)}catch(b){throw b;}finally{K[a.fd]=null}a.fd=null}
function Sc(a,b,c){if(a.fd===null)throw new Q(8);if(!a.seekable||!a.ba.ha)throw new Q(70);if(c!=0&&c!=1&&c!=2)throw new Q(28);a.position=a.ba.ha(a,b,c);a.Ua=[]}
function X(a,b){a=lc("/dev/"+a);var c=Dc(!!b);X.Ba??(X.Ba=64);var d=X.Ba++<<8|0;vc(d,{open(e){e.seekable=!1},close(){},read(e,f,g,n){for(var r=0,p=0;p<n;p++){try{var z=b()}catch(T){throw new Q(29);}if(z===void 0&&r===0)throw new Q(6);if(z===null||z===void 0)break;r++;f[g+p]=z}r&&(e.node.atime=Date.now());return r},write(e,f,g,n){for(var r=0;r<n;r++)try{(void 0)(f[g+r])}catch(p){throw new Q(29);}n&&(e.node.mtime=e.node.ctime=Date.now());return r}});Rc(a,c,d)}
var Y={},fa=(a,b,c)=>a?P((q(),Sa),a,b,c):"",Tc=18,M=void 0;function gb(a,b,c){if(m)return J(3,1,a,b,c);M=c;try{var d=V(a);switch(b){case 0:var e=O();if(e<0)break;for(;K[e];)e++;return Nc(d,e).fd;case 1:case 2:return 0;case 3:return d.flags;case 4:return e=O(),d.flags=d.flags&-289793|e&289792,0;case 12:return e=O(),(q(),Ra)[e+0>>1]=2,0;case 13:case 14:return 0}return-28}catch(f){if(typeof Y=="undefined"||f.name!=="ErrnoError")throw f;return-f.na}}
function hb(a,b,c){if(m)return J(4,1,a,b,c);M=c;try{var d=V(a);switch(b){case 21509:return d.tty?0:-59;case 21505:if(!d.tty)return-59;if(d.tty.la.Ka){a=[3,28,127,21,4,0,1,0,17,19,26,0,18,15,23,22,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0];var e=O();(q(),A)[e>>2]=25856;(q(),A)[e+4>>2]=5;(q(),A)[e+8>>2]=191;(q(),A)[e+12>>2]=35387;for(var f=0;f<32;f++)(q(),y)[e+f+17]=a[f]||0}return 0;case 21510:case 21511:case 21512:return d.tty?0:-59;case 21506:case 21507:case 21508:if(!d.tty)return-59;if(d.tty.la.La)for(e=O(),
q(),q(),q(),q(),a=[],f=0;f<32;f++)a.push((q(),y)[e+f+17]);return 0;case 21519:if(!d.tty)return-59;e=O();return(q(),A)[e>>2]=0;case 21520:return d.tty?-28:-59;case 21537:case 21531:e=O();if(!d.ba.Ja)throw new Q(59);return d.ba.Ja(d,b,e);case 21523:if(!d.tty)return-59;d.tty.la.Ma&&(f=[24,80],e=O(),(q(),Ra)[e>>1]=f[0],(q(),Ra)[e+2>>1]=f[1]);return 0;case 21524:return d.tty?0:-59;case 21515:return d.tty?0:-59;default:return-28}}catch(g){if(typeof Y=="undefined"||g.name!=="ErrnoError")throw g;return-g.na}}
function ib(a,b,c,d){if(m)return J(5,1,a,b,c,d);M=d;try{b=fa(b);var e=b;if(e.charAt(0)==="/")b=e;else{var f=a===-100?"/":V(a).path;if(e.length==0)throw new Q(44);b=f+"/"+e}var g=d?O():0;c&64&&(g&=~Tc);return Xa(b,c,g).fd}catch(n){if(typeof Y=="undefined"||n.name!=="ErrnoError")throw n;return-n.na}}
var jb=()=>Za(""),kb=a=>{var b=!ea;try{Atomics.wait((q(),A),0,0,0),b=!0}catch(c){}Ja(a,!k,1,b,3145728,!1);Ka()},Uc=a=>{a instanceof Xb||a=="unwind"||oa(1,a)},hc=a=>{if(!Qa&&!za)try{a()}catch(b){Uc(b)}finally{if(!(Qa||I>0))try{m?Hb()&&Pb(w):Ab(w)}catch(b){Uc(b)}}},La=a=>{ec||(Atomics.waitAsync((q(),A),a>>2,a).value.then(Na),a+=112,Atomics.store((q(),A),a>>2,1))},Na=()=>{var a=Hb();a&&hc(()=>{La(a);Rb()})},lb=(a,b)=>{a==b?setTimeout(Na):m?postMessage({Fa:a,ga:4}):(a=H[a])&&a.postMessage({ga:4})},Vc=
[],mb=(a,b,c,d,e,f,g)=>{Vc.length=0;b=e>>3;for(d=e+d>>3;b<d;){var n;(q(),C)[b++]?n=(q(),C)[b++]:n=(q(),Ta)[b++];Vc.push(n)}a=(0,Wc[a])(...Vc);if(f)a.then(r=>Mb(f,g,r));else return a},nb=()=>{I=0},ob=a=>{m?postMessage({ga:6,Sa:a}):fc(H[a])},pb=a=>{l&&(a=H[a],a.ref(),a.Ra=1)},L={},vb=()=>performance.timeOrigin+performance.now();
function qb(a,b){if(m)return J(6,1,a,b);L[a]&&(clearTimeout(L[a].id),delete L[a]);if(!b)return 0;var c=setTimeout(()=>{delete L[a];hc(()=>Qb(a,performance.timeOrigin+performance.now()))},b);L[a]={id:c,hb:b};return 0}
var t=(a,b,c)=>sc(a,(q(),Sa),b,c),rb=(a,b,c,d)=>{var e=(new Date).getFullYear(),f=(new Date(e,0,1)).getTimezoneOffset();e=(new Date(e,6,1)).getTimezoneOffset();var g=Math.max(f,e);(q(),B)[a>>2]=g*60;(q(),A)[b>>2]=Number(f!=e);b=n=>{var r=Math.abs(n);return`UTC${n>=0?"-":"+"}${String(Math.floor(r/60)).padStart(2,"0")}${String(r%60).padStart(2,"0")}`};a=b(f);b=b(e);e<f?(t(a,c,17),t(b,d,17)):(t(a,d,17),t(b,c,17))},Xc=1;
function sb(a,b,c){if(!(a>=0&&a<=3))return 28;if(a===0)a=Date.now();else if(Xc)a=performance.timeOrigin+performance.now();else return 52;a=Math.round(a*1E3*1E3);(q(),C)[c>>3]=BigInt(a);return 0}
var Z=()=>{var a="Blocking on the main thread is very dangerous, see https://emscripten.org/docs/porting/pthreads.html#blocking-on-the-main-browser-thread";Z.ya||(Z.ya={});Z.ya[a]||(Z.ya[a]=1,l&&(a="warning: "+a),u(a))},tb=()=>{l||k||(Z(),Za("Blocking on the main thread is not allowed by default. See https://emscripten.org/docs/porting/pthreads.html#blocking-on-the-main-browser-thread"))},ub=()=>{I+=1;throw"unwind";},wb=a=>{var b=(q(),Sa).length;a>>>=0;if(a<=b||a>2147483648)return!1;for(var c=1;c<=
4;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);a:{d=(Math.min(2147483648,Math.ceil(Math.max(a,d)/65536)*65536)-x.buffer.byteLength+65535)/65536|0;try{x.grow(d);Aa();var e=1;break a}catch(f){}e=void 0}if(e)return!0}return!1},Yc={},$c=()=>{if(!Zc){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:(globalThis.navigator?.language??"C").replace("-","_")+".UTF-8",_:na},b;for(b in Yc)Yc[b]===void 0?delete a[b]:a[b]=Yc[b];var c=[];for(b in a)c.push(`${b}=${a[b]}`);
Zc=c}return Zc},Zc;function yb(a,b){if(m)return J(7,1,a,b);var c=0,d=0,e;for(e of $c()){var f=b+c;(q(),B)[a+d>>2]=f;c+=t(e,f,Infinity)+1;d+=4}return 0}function zb(a,b){if(m)return J(8,1,a,b);var c=$c();(q(),B)[a>>2]=c.length;a=0;for(var d of c)a+=ka(d)+1;(q(),B)[b>>2]=a;return 0}function Bb(a){if(m)return J(9,1,a);try{var b=V(a);dc(b);return 0}catch(c){if(typeof Y=="undefined"||c.name!=="ErrnoError")throw c;return c.na}}
function Cb(a,b,c,d){if(m)return J(10,1,a,b,c,d);try{a:{var e=V(a);a=b;for(var f,g=b=0;g<c;g++){var n=(q(),B)[a>>2],r=(q(),B)[a+4>>2];a+=8;var p=e,z=(q(),y),T=n,aa=r,F=f;if(aa<0||F<0)throw new Q(28);if(p.fd===null)throw new Q(8);if((p.flags&2097155)===1)throw new Q(8);if((p.node.mode&61440)===16384)throw new Q(31);if(!p.ba.read)throw new Q(28);var ba=typeof F!="undefined";if(!ba)F=p.position;else if(!p.seekable)throw new Q(70);var ca=p.ba.read(p,z,T,aa,F);ba||(p.position+=ca);var G=ca;if(G<0){var da=
-1;break a}b+=G;if(G<r)break;typeof f!="undefined"&&(f+=G)}da=b}(q(),B)[d>>2]=da;return 0}catch(N){if(typeof Y=="undefined"||N.name!=="ErrnoError")throw N;return N.na}}function Db(a,b,c,d){if(m)return J(11,1,a,b,c,d);b=b<-9007199254740992||b>9007199254740992?NaN:Number(b);try{if(isNaN(b))return 22;var e=V(a);Sc(e,b,c);(q(),C)[d>>3]=BigInt(e.position);e.wa&&b===0&&c===0&&(e.wa=null);return 0}catch(f){if(typeof Y=="undefined"||f.name!=="ErrnoError")throw f;return f.na}}
function Eb(a,b,c,d){if(m)return J(12,1,a,b,c,d);try{a:{var e=V(a);a=b;for(var f,g=b=0;g<c;g++){var n=(q(),B)[a>>2],r=(q(),B)[a+4>>2];a+=8;var p=e,z=(q(),y),T=n,aa=r,F=f;if(aa<0||F<0)throw new Q(28);if(p.fd===null)throw new Q(8);if((p.flags&2097155)===0)throw new Q(8);if((p.node.mode&61440)===16384)throw new Q(31);if(!p.ba.write)throw new Q(28);p.seekable&&p.flags&1024&&Sc(p,0,2);var ba=typeof F!="undefined";if(!ba)F=p.position;else if(!p.seekable)throw new Q(70);var ca=p.ba.write(p,z,T,aa,F,void 0);
ba||(p.position+=ca);var G=ca;if(G<0){var da=-1;break a}b+=G;if(G<r)break;typeof f!="undefined"&&(f+=G)}da=b}(q(),B)[d>>2]=da;return 0}catch(N){if(typeof Y=="undefined"||N.name!=="ErrnoError")throw N;return N.na}}S=Array(4096);Pc(R,"/");W("/tmp");W("/home");W("/home/web_user");
(function(){W("/dev");vc(259,{read:()=>0,write:(d,e,f,g)=>g,ha:()=>0});Rc("/dev/null",259);uc(1280,xc);uc(1536,yc);Rc("/dev/tty",1280);Rc("/dev/tty1",1536);var a=new Uint8Array(1024),b=0,c=()=>{b===0&&(oc(a),b=a.byteLength);return a[--b]};X("random",c);X("urandom",c);W("/dev/shm");W("/dev/shm/tmp")})();
(function(){W("/proc");var a=W("/proc/self");W("/proc/self/fd");Pc({ka(){var b=Ac(a,"fd",16895,73);b.ba={ha:R.ba.ha};b.da={lookup(c,d){c=+d;var e=V(c);c={parent:null,ka:{Da:"fake"},da:{readlink:()=>e.path},id:c+1};return c.parent=c},readdir(){return Array.from(K.entries()).filter(([,c])=>c).map(([c])=>c.toString())}};return b}},"/proc/self/fd")})();m||(h.wasmMemory?x=h.wasmMemory:x=new WebAssembly.Memory({initial:1024,maximum:32768,shared:!0}),Aa());h.print&&(ya=h.print);h.printErr&&(u=h.printErr);
h.UTF8ToString=fa;h.stringToUTF8=t;var Wc=[Fb,cc,jc,gb,hb,ib,qb,yb,zb,Bb,Cb,Db,Eb],la,ja,ha,Hb,Ib,Jb,Ja,Kb,Oa,Lb,ia,Mb,Nb,Ob,Pb,Qb,Rb,Sb,Tb,Ub,Vb,Wb,eb;function ad(a=[]){var b=Ib;I+=1;a.unshift(na);var c=a.length,d=Ub((c+1)*4),e=d,f;for(f of a){a=(q(),B);var g=e>>2,n=f,r=ka(n)+1,p=Ub(r);t(n,p,r);a[g]=p;e+=4}(q(),B)[e>>2]=0;try{var z=b(c,d);Ab(z,!0)}catch(T){Uc(T)}}
function Ha(){var a=ma;if(!(Ec>0))if(m)Ba?.(h),Ua();else{for(var b=Zb;b.length>0;)b.shift()(h);Ec>0||(h.calledRun=!0,za||(Ua(),Ba?.(h),ad(a)))}}var D;m||(D=await (Ga()),Ha());Pa?moduleRtn=h:moduleRtn=new Promise((a,b)=>{Ba=a;Ca=b});
;return moduleRtn}export default Fsf_14_Web;var isPthread=globalThis.name=="em-pthread";var isNode=globalThis.process?.versions?.node&&globalThis.process?.type!="renderer";if(isNode)isPthread=(await import("node:worker_threads")).workerData==="em-pthread";isPthread&&Fsf_14_Web();
