#!/usr/bin/env node
// Build docs/CHANGELOG.md, newest first, from the GitHub releases (read-only GET, no token needed:
// two pages at 100 per page is well inside the 60/hour anonymous limit) plus docs/RELEASES-ARCHIVE.md,
// which holds the notes of releases deleted to reclaim asset storage. A version on both sides is
// taken from the live release.
//
//   node tools/changelog.mjs                          -> docs/CHANGELOG.md
//   node tools/changelog.mjs --out /tmp/CHANGELOG.md --archive path/to/RELEASES-ARCHIVE.md
import fs from 'node:fs';
import path from 'node:path';
import {fileURLToPath} from 'node:url';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const REPO = 'IchNukeDichWeg/Mephisto';

// ==== pure (test_popup_logic.js slices from here to the end marker and runs it) ====
// "v3.1.315" / "Mephisto 3.1.57 - ..." -> [3,1,315]; null for tags that are not versions (models-v1)
function versionOf(text) {
    const m = /(?:^|[^\w.])v?(\d+)\.(\d+)\.(\d+)\b/.exec(text || '');
    return m ? [+m[1], +m[2], +m[3]] : null;
}
const byVersionDesc = (a, b) => b.v[0] - a.v[0] || b.v[1] - a.v[1] || b.v[2] - a.v[2];

// Release bodies are rendered on GitHub with every newline a line break; a .md file joins them into
// one paragraph, which ran the "Checks | ... Harness | ..." stats block together. Hard breaks
// restore the release page's look (never inside code fences, where the spaces would be literal).
function releaseBreaks(body) {
    const lines = String(body || '').replace(/\r\n?/g, '\n').trim().split('\n');
    let fence = false;
    return lines.map((l, i) => {
        if (/^\s*```/.test(l)) fence = !fence;
        // demote h1/h2 so a note cannot break the changelog's own outline
        const out = fence ? l : l.replace(/^#{1,2} /, '### ');
        const next = lines[i + 1];
        return (!fence && l.trim() && next && next.trim() && !/^\s*```/.test(l)) ? out + '  ' : out;
    }).join('\n');
}

// The archive is `---`-separated entries, each opening with its "## <version> ..." heading. It is
// split on the separators, not on "## ": old notes carry their own "## Install" / "## What's new
// since 3.1.41" inside, and the second one would otherwise pass for a version. Chunks that do not
// open with a versioned heading (the preamble, "Second pass: ...") are narrative and dropped.
function archiveEntries(text) {
    return String(text || '').replace(/\r\n?/g, '\n').split(/^-{3,}[ \t]*$/m).map(chunk => {
        const [head, ...rest] = chunk.trim().split('\n');
        if (!/^## /.test(head || '')) return null;
        return {v: versionOf(head), head: head.replace(/^##\s*/, ''),
                body: rest.join('\n').trim().replace(/^#{1,2} /gm, '### ')};
    }).filter(e => e && e.v);
}

function renderChangelog(releases, archiveText) {
    const live = releases.filter(r => !r.draft && versionOf(r.tag_name)).map(r => ({
        v: versionOf(r.tag_name),
        head: (r.name && versionOf(r.name) ? r.name : `${r.tag_name}${r.name ? ' - ' + r.name : ''}`).trim(),
        body: `*Released ${String(r.published_at || '').slice(0, 10)}${r.prerelease ? ', pre-release' : ''}.*\n\n`
            + releaseBreaks(r.body),
    }));
    const seen = new Set(live.map(e => e.v.join('.')));
    const archived = archiveEntries(archiveText).filter(e => !seen.has(e.v.join('.')));
    const all = [...live, ...archived].sort(byVersionDesc);
    return [
        '# Changelog',
        '',
        `Newest first: ${live.length} releases from the Releases page`
            + (archived.length ? ` and ${archived.length} archived in [RELEASES-ARCHIVE.md](RELEASES-ARCHIVE.md)` : '')
            + '. Generated by `tools/changelog.mjs`; do not edit by hand.',
        '',
        ...all.map(e => `## ${e.head}\n\n${e.body}\n`),
    ].join('\n');
}
// ==== end pure ====

async function allReleases() {
    const out = [];
    for (let page = 1; ; page++) {
        const r = await fetch(`https://api.github.com/repos/${REPO}/releases?per_page=100&page=${page}`,
            {headers: {Accept: 'application/vnd.github+json'}});
        if (!r.ok) throw new Error(`GitHub API ${r.status} on page ${page}`);
        const batch = await r.json();
        out.push(...batch);
        if (batch.length < 100) return out;
    }
}

async function main() {
    const o = {out: path.join(ROOT, 'docs/CHANGELOG.md'), archive: path.join(ROOT, 'docs/RELEASES-ARCHIVE.md')};
    const argv = process.argv.slice(2);
    for (let i = 0; i < argv.length; i++) {
        if (argv[i] === '--out') o.out = path.resolve(argv[++i]);
        else if (argv[i] === '--archive') o.archive = path.resolve(argv[++i]);
        else throw new Error(`unknown option ${argv[i]}`);
    }
    const releases = await allReleases();
    // the archive only exists in the public repo; without it the changelog is the live releases alone
    const archive = fs.existsSync(o.archive) ? fs.readFileSync(o.archive, 'utf8') : '';
    if (!archive) console.log(`no archive at ${o.archive} - live releases only`);
    const md = renderChangelog(releases, archive);
    fs.mkdirSync(path.dirname(o.out), {recursive: true});
    fs.writeFileSync(o.out, md);
    console.log(`${o.out}: ${md.length} bytes, ${(md.match(/^## /gm) || []).length} versions`);
}

main().catch(e => { console.error('changelog:', e.message); process.exit(1); });
